name = "anssi_high"
description = "ANSSI-BP-028 (high)"
version = "0.1.62"

[[packages]]
name = "tmux"
version = "*"

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "Thequickbrownfox42!"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]

[customizations.openscap]
profile_id = "bp28_high"
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"

