name = "basic"
description = "Basic image with logins"
version = "0.0.1"
modules = []
groups = []
distro = ""

[customizations]

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$g.tmNsWTbgM1bsgP$kVaWMUpOEjxPMQLMI979tsOzduaXdXV26P4E7Jw76WBQ9hXz3iTswFpRd3RfWEecwzJwWP12fqW6dmV8aWC/p."
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]