###############################################################################
# Info
###############################################################################

name = "oscap"
description = "osbuild image with oscap build remediation - CIS benchmark"
version = "0.0.1"
modules = []
groups = []
distro = ""

###############################################################################
# Packages
###############################################################################

[[packages]]
name = "openscap-scanner"
version = "*"

[[packages]]
name = "scap-security-guide"
version = "*"

[[packages]]
name = "aide"
version = "*"

[[packages]]
name = "sudo"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "rsyslog"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "libselinux"
version = "*"

###############################################################################
# Users
###############################################################################

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]

###############################################################################
# OpenSCAP
###############################################################################

[customizations.openscap]
data_dir = "/home/kingsley/openscap_data"
profile_id = "cis"
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"

###############################################################################
# Filesystem
###############################################################################

[[customizations.filesystem]]
mountpoint = "/"
size = 2147483648

[[customizations.filesystem]]
mountpoint = "/var"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/var/log"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/usr"
size = 4294967296

[[customizations.filesystem]]
mountpoint = "/home"
size = 2147483648

[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/tmp"
size = 131072000

###############################################################################
# Other customizations
###############################################################################

[customizations.kernel]
append = "audit_backlog_limit=8192 audit=1"

[customizations.services]
enabled = ["crond","firewalld","rsyslog","auditd"]
disabled = ["snmpd","smb","squid","cups","ypserv","rsyncd","nfs-server","rpcbind","slapd","dovecot","httpd","vsftpd","named","dhcpd","avahi-daemon","autofs"]