###############################################################################
# Info
###############################################################################

name = "repos"
description = "Custom repositories"
version = "0.0.1"
modules = []
groups = []
distro = ""

###############################################################################
# Users
###############################################################################

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]

###############################################################################
# Repositories
###############################################################################

[[customizations.repositories]]
id = "1password"
name="1Password Stable Channel"
baseurl=[ "https://downloads.1password.com/linux/rpm/stable/$basearch" ]
gpgcheck=true
gpgkey=[ "https://downloads.1password.com/linux/keys/1password.asc" ]

[[customizations.repositories]]
id = "Charm"
name="charm"
baseurl=[ "https://repo.charm.sh/yum/" ]
gpgcheck=false
