name = "pci"
description = "PCI-DSS for Red Hat Enterprise Linux 8"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "aide"
version = "*"

[customizations]

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]


[customizations.openscap]
data_dir = "/home/kingsley/openscap_data"
profile_id = "pci-dss"
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
