name = "rhel-stig"
description = "DISA STIG for Red Hat Enterprise Linux 8"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "aide"
version = "*"

[customizations]

[[customizations.filesystem]]
mountpoint = "/"
size = 2147483648

[[customizations.filesystem]]
mountpoint = "/var"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/var/log"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/usr"
size = 2147483648

[[customizations.filesystem]]
mountpoint = "/home"
size = 2147483648

[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 131072000

[[customizations.filesystem]]
mountpoint = "/tmp"
size = 131072000

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]


[customizations.openscap]
data_dir = "/home/kingsley/openscap_data"
profile_id = "stig"

[[packages]]
name = "rng-tools"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "opensc"
version = "*"

[[packages]]
name = "openssl-pkcs11"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "rsyslog-gnutls"
version = "*"

[[packages]]
name = "rsyslog"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "policycoreutils"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "usbguard"
version = "*"

[customizations.kernel]
append = "slub_debug=P page_poison=1 vsyscall=none pti=on audit_backlog_limit=8192 audit=1"

[customizations.services]
enable = ["usbguard","sshd","rngd","fapolicyd","firewalld","rsyslog","auditd"]
disable = ["kdump","systemd-coredump","autofs","debug-shell"]