name = "rhel-cui"
description = "CUI for Red Hat Enterprise Linux 8"
version = "0.0.1"
modules = []
groups = []
distro = ""

[customizations]

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]

[customizations.openscap]
profile_id = "cui"
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"

[[customizations.filesystem]]
mountpoint = "/home"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/var"
size = 3221225472

[[customizations.filesystem]]
mountpoint = "/var/log"
size = 5368709120

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 10737418240

[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 1073741824

[[packages]]
name = "sudo"
version = "*"

[[packages]]
name = "dnf-plugin-subscription-manager"
version = "*"

[[packages]]
name = "gnutls-utils"
version = "*"

[[packages]]
name = "openscap-scanner"
version = "*"

[[packages]]
name = "scap-security-guide"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "dnf-automatic"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "rsyslog"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "policycoreutils-python-utils"
version = "*"

[[packages]]
name = "policycoreutils"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[[packages]]
name = "chrony"
version = "*"

[[packages]]
name = "openssh-clients"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "usbguard"
version = "*"

[customizations.kernel]
append = "slub_debug=P page_poison=1 vsyscall=none pti=on random.trust_cpu=on audit_backlog_limit=8192 audit=1 fips=1 boot=/dev/sda4"

[customizations.services]
enabled = ["usbguard","fapolicyd","firewalld","auditd"]
disabled = ["kdump","systemd-coredump","debug-shell"]

