#!/usr/bin/python3
import argparse
import subprocess
import sys

from devtools import echo, load_json


def get_benchmark(distro, profile):
    profiles = load_json("./config/data/oscap-profiles.json")
    try:
        return profiles[distro][profile]
    except Exception:
        echo(f"{profile} not available for {distro} distro", "ERROR")
        sys.exit(1)


def run(input_file, distro, profile):
    p = get_benchmark(distro, profile)
    cmd = [
        "oscap", "xccdf", "generate", "fix",
        "--profile", p["profile"],
        "--fix-type", "blueprint",
        input_file
    ]
    subprocess.run(cmd)
    return 0


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", help="Input file", type=str)
    parser.add_argument("-d", "--distro", help="Distro", type=str)
    parser.add_argument("-b", "--profile", help="Openscap profile", type=str)
    return parser.parse_args()


def blueprint():
    args = parse_args()
    sys.exit(
        run(
            args.input,
            args.distro,
            args.profile
        )
    )
