name = "fedora-ospp"
description = "OSPP - Protection Profile for General Purpose Operating Systems (Fedora)"
version = "0.0.1"
modules = []
groups = []
distro = ""
 
[[packages]]
name = "openscap-scanner"
version = "1.3.6-3.fc35.x86_64"

[[packages]]
name = "openscap-utils"
version = "1.3.6-3.fc35.x86_64"

[[packages]]
name = "scap-security-guide"
version = "*"

[customizations]

[customizations.openscap]
profile_id = "xccdf_org.ssgproject.content_profile_ospp"
datastream = "/usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml"

[[customizations.user]]
name = "kingsley"
description = "Administrator account"
password = "$6$b/oXN5xGcuTmVdui$9T/FrBmUkcEHK5sLhg/E6sFXKa84zU3cLum3DPwppNzFhtAl6yD6SEZRe3v6hpmHtkVXYyN6qGXINJVntHpwN/"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCWAwAqV3weCALKWrSAAHir+oIga1TU5VL4hnjWWU2x gzuccare@redhat.com"
home = "/home/kingsley/"
groups = ["wheel"]

[[packages]]
name = "dnf-automatic"
version = "*"

[[packages]]
name = "screen"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[[packages]]
name = "rng-tools"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "rsyslog"
version = "*"

[[packages]]
name = "lynx"
version = "*"

[[packages]]
name = "plymouth"
version = "*"

[customizations.kernel]
append = "slub_debug=P page_poison=1 vsyscall=none pti=on audit_backlog_limit=8192 audit=1"

[customizations.services]
enabled = ["rngd","firewalld","auditd","rsyslog"]
disabled = ["systemd-coredump","debug-shell"]