#!/usr/bin/expect -f

# Wait enough (forever) until a long-time boot
set timeout -1

spawn ${qemu}

expect "login: "
send "kingsley\n"

expect "Password: "
send "password42\n"

expect "$ "
send "journalctl -fa\n"

expect "something that will never happen"
send "exit\n"
